---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: hardening

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: local
  connection: local
  become: no
  vars:
    state: 'present'
  tasks:
    - import_tasks: roles/hardening/tasks/apply.yaml
